apiVersion: v1
kind: Service
metadata:
  name: friends-api-service
  labels:
    run: friends-api-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: friends-api
